# Build kwal.js from modules
# Run from sdroot/webgui-src folder

$modules = @(
    "js/namespace.js",
    "js/state.js",
    "js/audio.js",
    "js/brightness.js",
    "js/modal.js",
    "js/sd.js",
    "js/pattern.js",
    "js/colorpicker.js",
    "js/colors.js",
    "js/ota.js",
    "js/status.js",
    "js/health.js",
    "js/log.js",
    "js/mp3grid.js",
    "js/sse.js",
    "js/main.js"
)

# Output ONLY to sdroot - NO local copy to prevent accidental editing
$sdroot_output = "../kwal.js"
$version = "260213A"

# Header with DO NOT EDIT warning (in case Copilot is being a cunt)
$header = @"
/*
 * ╔═══════════════════════════════════════════════════════════════╗
 * ║  DO NOT EDIT THIS FILE - COPILOT MEANS YOU                    ║
 * ║  Source: sdroot/webgui-src/js/*.js                            ║
 * ║  Build:  cd webgui-src; .\build.ps1                           ║
 * ╚═══════════════════════════════════════════════════════════════╝
 *
 * Kwal WebGUI v$version - Built $(Get-Date -Format 'yyyy-MM-dd HH:mm')
 */
"@

$content = $header + "`n"

# Concatenate modules
foreach ($mod in $modules) {
    if (Test-Path $mod) {
        $content += "`n// === $mod ===`n"
        $content += Get-Content $mod -Raw
        $content += "`n"
    } else {
        Write-Host "WARNING: $mod not found" -ForegroundColor Yellow
    }
}

# Write ONLY to sdroot (no local kwal.js to prevent Copilot from editing it)
# Inject version into content (replaces {{VERSION}} placeholder in namespace.js)
$content = $content -replace '\{\{VERSION\}\}', $version
Set-Content -Path $sdroot_output -Value $content -Encoding UTF8

# Remove local kwal.js if it exists (cleanup from old builds)
if (Test-Path "kwal.js") {
    Remove-Item "kwal.js"
    Write-Host "Removed stale webgui-src/kwal.js" -ForegroundColor Yellow
}

Write-Host "Built $sdroot_output ($((Get-Content $sdroot_output).Count) lines)" -ForegroundColor Green

# Cache-bust: update kwal.js?v= in index.html
$indexPath = "../index.html"
if (Test-Path $indexPath) {
    $html = Get-Content $indexPath -Raw
    $html = $html -replace 'kwal\.js\?v=[^"]+', "kwal.js?v=$version"
    Set-Content -Path $indexPath -Value $html -Encoding UTF8 -NoNewline
    Write-Host "Updated index.html cache-bust to v=$version" -ForegroundColor Green
}
